### ISSUE TITLE
Compatibility for CommonJs and ESM

### ISSUE THREAD

**Issue by gentlementlegen** [ubiquity/ubiquibot-logger#19]
The package is currently only compiled for ESM projects, which implies adding the `"type": "module"`. This usually breaks projects that are using older techs requiring `"type": "commonjs"`, which is broadly used within our organization and the packages we include. It would be better to offer both solutions, as this package doesn't require to be in ESM to work properly.

Tasks to be carried out:
- bundle for both ESM and CommonJs
- pack them properly with input entries
- make sure it works with `module` and `commonjs`

**Comment by 0x4007** [comment]
I think setting permissions is broken last time we tried. Can make you billing manager though. Will need to try when back on computer later.

**Comment by gentlementlegen** [comment]
@0x4007 Well I am billing manager within Ubiquity Org, so the issue might be different. Yes I recall it being broken as well. It's not urgent I guess, just a bit annoying 😄

**Comment by 0x4007** [comment]
Why is my comment relevance 0 on v2? I expect it to be low but not 0

**Comment by gentlementlegen** [comment]
@0x4007 miggt be due to either Gpt4 or a multiplier that makes it 0, will have a look

**Comment by 0x4007** [comment]
Relevance made it `0` but ChatGPT I wouldn't expect to return a perfect `0`

**Comment by gentlementlegen** [comment]
I think I defaulted to `0` if there is any bug or crash during the evaluation of relevance to avoid major issues on the final result, which might be the reason.

**Comment by 0x4007** [comment]
In my implementation I made it default to 1 in case of error. Seems unfair to the contributor to not get any credit if there's a bug with the software.

**Comment by gentlementlegen** [comment]
Added this to the specification.
