### ISSUE TITLE
Redundant OK Logs

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/ubiquibot-logger#3]
@gitcoindev I'm in the middle of a few things now and I'm hoping you can sync a change for me before I forget and mess things up.

https://github.com/pavlovcik/ubiquibot/blob/85177d0be5f5f0dde874f4164426a7c7d4702ea1/src/adapters/supabase/helpers/tables/logs.ts#L274

This was redundantly logging every type of log as "ok" in the console, causing a lot of noise.

**Comment by gitcoindev** [comment]
All right,this log entry will be removed, thank you for letting me know.
